### PR TITLE
Fixed Python3 support.

### PR DESCRIPTION
**Pull request by tell-k**
django-bouncy authors.

First, thanks for the awesome tool.
I encountered errors such as the following.

```
(django-bouncy) tell-k-no-MacBook-Pro:django-bouncy tell_k$ tox -e py35-django18
EE....
======================================================================
ERROR: Test a non-valid keyfile
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tell_k/Work/github.com/tell-k/django-bouncy/.tox/py35-django18/lib/python3.5/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/Users/tell_k/Work/github.com/tell-k/django-bouncy/django_bouncy/tests/utils.py", line 36, in test_bad_keyfile
    utils.grab_keyfile('http://www.fakeurl.com')
  File "/Users/tell_k/Work/github.com/tell-k/django-bouncy/django_bouncy/utils.py", line 82, in grab_keyfile
    certificates = pem.parse(smart_str(pemfile))
  File "/Users/tell_k/Work/github.com/tell-k/django-bouncy/.tox/py35-django18/lib/python3.5/site-packages/pem/_core.py", line 104, in parse
    for match in _PEM_RE.finditer(pem_str)]
TypeError: cannot use a bytes pattern on a string-like object

======================================================================
ERROR: Test the grab_keyfile plugin
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tell_k/Work/github.com/tell-k/django-bouncy/.tox/py35-django18/lib/python3.5/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/Users/tell_k/Work/github.com/tell-k/django-bouncy/django_bouncy/tests/utils.py", line 23, in test_grab_keyfile
    result = utils.grab_keyfile('http://www.fakeurl.com')
  File "/Users/tell_k/Work/github.com/tell-k/django-bouncy/django_bouncy/utils.py", line 82, in grab_keyfile
    certificates = pem.parse(smart_str(pemfile))
  File "/Users/tell_k/Work/github.com/tell-k/django-bouncy/.tox/py35-django18/lib/python3.5/site-packages/pem/_core.py", line 104, in parse
    for match in _PEM_RE.finditer(pem_str)]
TypeError: cannot use a bytes pattern on a string-like object

----------------------------------------------------------------------
Ran 35 tests in 0.109s

FAILED (errors=2)
```

The cause of this error is because `django.utils.smart_str` cannot return bytes when using python3.
You should use `django.utils.smart_bytes` when supporting python2 and python3.

see also https://docs.djangoproject.com/en/1.10/ref/utils/#django.utils.encoding.smart_str

In addition, I updated tox.ini and .travis.yml so that I can also test it with Django 1.10 :)
thx.

### CODE REVIEW

**Comment by nickcatal** [comment]
This looks great. Thanks!

**Comment by tell-k** [comment]
@nickcatal  Hi. I am waiting for the next version. When will it be released?

**Comment by nickcatal** [comment]
@tell-k just released it. sorry

https://pypi.python.org/pypi/django-bouncy/0.2.6

**Comment by tell-k** [comment]
@nickcatal Thank you for your immediate action :)

**Pull request merged**
