### PR TITLE
Here is the missing migration that fixes issue #14

### PR DESCRIPTION
**Pull request by smeinel**
For reference: #14 - Migrations are not fully in sync with Models

### CODE REVIEW

**Comment by nickcatal** [comment]
Good catch.

Boilerplate CLA language below:

In order to submit new code we now require contributors to sign our Contributor License Agreement (CLA.)

If this commit was part of your individual work, you can sign the [Individual Contributor License Agreement](https://ofa.github.io/cla-individual.html).
If this commit was part of your work for an organization or entity, that entity can sign our [Entity Contributor License Agreement](https://ofa.github.io/cla-entity.html).
We also provide [a useful FAQ](https://ofa.github.io/cla-faq.html) explaining things.

Once we get that form filled out I'll merge this in right away and push to the package index.

Thanks!

**Comment by smeinel** [comment]
Hi, I'm out of the office this week, so I'll work on this Moday.

Thanks!

**Comment by smeinel** [comment]
@nickcatal I've passed the message up the chain here at work regarding the Entity CLA. Hopefully it can be resolved quickly.

**Comment by smeinel** [comment]
@nickcatal According to the folks here at Caltech that handle legal matters, the Entity CLA should have been submitted to you today. Thanks!

**Pull request closed without merging**
